### ISSUE TITLE
反序列化测试无效

### ISSUE THREAD

**Issue by seabird1992** [qi4L/yongyouScan.go#4]
试了一堆用友站，测试反序列化一个没有效果，估计你那个代码没写完整反序列化PAYLOAD吧

**Comment by qi4L** [comment]
![image](https://github.com/qi4L/yongyouScan.go/assets/75202638/fd6db6e3-f738-4988-9b5a-17c912e2df1a)

**Comment by qi4L** [comment]
你在仔细看下吧

**Comment by qi4L** [comment]
![image](https://github.com/qi4L/yongyouScan.go/assets/75202638/f45d4bf1-75ee-49b4-8c69-29c6f664fe0a)

**Comment by qi4L** [comment]
你在仔细看下吧

**Comment by qi4L** [comment]
还有别估计了，看下代码再说呗，也可能是没用CC依赖

**Comment by qi4L** [comment]
再看下dnslog平台通不通
